# Generated by Django 5.2.4 on 2025-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='beginner',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
