# Generated by Django 5.2.4 on 2025-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqapp', '0002_intermediate_pro_rename_member_beginner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pro',
            name='content',
            field=models.TextField(),
        ),
    ]
